name: Sync Upstream and Build Docker Image

on:
  schedule:
    - cron: '0 4 * * *' # 每天凌晨 4 点
  workflow_dispatch:

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Increase Git buffer size
        run: |
          git config --global http.postBuffer 524288000
          git config --global http.maxRequests 100

      - name: Sync upstream
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add upstream https://git.unlock-music.dev/um/web.git || true
          for i in {1..3}; do git fetch upstream && break || sleep 5; done
          git merge upstream/main --allow-unrelated-histories --no-edit || true
          git push origin main || true

      - name: Check if repo updated
        id: check_update
        run: |
          if git log HEAD@{1}..HEAD --oneline | grep .; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Force build on first run
        id: first_run
        run: |
          if [ ! -f .github/.workflow-first-run ]; then
            echo "force=true" >> $GITHUB_OUTPUT
            mkdir -p .github
            echo "done" > .github/.workflow-first-run
            git add .github/.workflow-first-run
            git commit -m "Add workflow first run marker" || true
            git push || true
          else
            echo "force=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        if: steps.check_update.outputs.updated == 'true' || steps.first_run.outputs.force == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.check_update.outputs.updated == 'true' || steps.first_run.outputs.force == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.check_update.outputs.updated == 'true' || steps.first_run.outputs.force == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.check_update.outputs.updated == 'true' || steps.first_run.outputs.force == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: golne/un-music:latest
